### ISSUE TITLE
Form not being intercepted if the it is submitted by javascript

### ISSUE THREAD

**Issue by kevinresol** [jasononeil/hxpushstate#6]
such as

``` html
<select onchange="this.form.submit()"></select>
```

or

``` javascript
$('#my-form').submit();
```

I think it is because the event is not fired at document level which PushState listens to

**Comment by jasononeil** [comment]
It seems to be that `HtmlFormElement.submit()` just doesn't trigger events:

http://stackoverflow.com/questions/17626661/htmlformelement-submit-and-reset-methods-relation-with-event-handlers

That's a bit frustrating as it means we'll have to explicitly intercept events somewhere.  Perhaps we need a method like:

```
PushState.submitForm( form );

static function submitForm( form:HTMLFormElement ) {
    if ( pushstateIsSupported ) {
        interceptFormSubmit( form );
    }
    else form.submit();
}
```

Do you have any other thoughts?

**Comment by kevinresol** [comment]
Well, in that case it is not something we can fix. Your solution could be one of the way. On the other hand, [this page (scroll to bottom)](http://bugs.jquery.com/ticket/4930) shows that jQuery will trigger `onsubmit` specified in html element (I'm not very sure about this, untested). But if that's true, we may make use of that if the user is using jQuery (which should be very common if anyone is writing a js front-end) e.g.:

```html
<form id="myform" onsubmit="PushState.interceptForm(event)" action="">
  ...
</form>
```

And in PushState just extract the form object from the event. (but again, the whole concept is untested)

**Comment by kevinresol** [comment]
Cleaning up my old issues and I think this is no longer needed.
